# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rise的自言自语
email: risezhang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  想到神马写神马
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.risezhang.com" # the base hostname & protocol for your site
twitter_username: risezhang
github_username:  risezhang

# Build settings
markdown: kramdown
